version: "3.8"

services:
  uptime-kuma-${USERNAME}:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma-${USERNAME}
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        limits:
          memory: 350M
    networks:
      - web
    labels:
      # Enable Traefik routing
      - "traefik.enable=true"

        # HTTP to HTTPS redirect
      - "traefik.http.routers.${USERNAME}-http.rule=Host(`${USERNAME}.monitor.bigzee.app`)"
      - "traefik.http.routers.${USERNAME}-http.entrypoints=web"
      - "traefik.http.routers.${USERNAME}-http.middlewares=${USERNAME}-https-redirect"
      - "traefik.http.middlewares.${USERNAME}-https-redirect.redirectscheme.scheme=https"

      # HTTPS configuration
      - "traefik.http.routers.${USERNAME}.rule=Host(`${USERNAME}.monitor.bigzee.app`)"
      - "traefik.http.routers.${USERNAME}.entrypoints=websecure"
      - "traefik.http.routers.${USERNAME}.tls=true"
      - "traefik.http.routers.${USERNAME}.tls.certresolver=cloudflare"

      # Specify container port to route to
      - "traefik.http.services.${USERNAME}.loadbalancer.server.port=3001"

networks:
  web:
    external: true
